apiVersion: training.eduk8s.io/v1alpha1
kind: Workshop
metadata:
  name: lab-image-security
spec:
  vendor: eduk8s.io
  title: Image Security
  description: An interactive workshop on constructing secure images.
  url: https://github.com/eduk8s-labs/lab-image-security
  content: github.com/eduk8s-labs/lab-image-security
  duration: 60m
  session:
    budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      docker:
        enabled: true
      registry:
        enabled: true
